###  基本数据类型

IntTensor of size()

FloatTensor of size()

IntTensor of size[d1,d2,...]

FloatTensor of size[d1,d2,...]

注：pytorch没有string类型

###  类型检查

In [32]:
import torch
import numpy as np

In [3]:
a = torch.randn(2,3)

In [4]:
a.type()

'torch.FloatTensor'

In [5]:
type(a)

torch.Tensor

In [6]:
isinstance(a,torch.FloatTensor)

True

In [8]:
isinstance(a,torch.cuda.DoubleTensor)

False

In [11]:
a = a.cuda()

In [12]:
a.type()

'torch.cuda.FloatTensor'

In [13]:
isinstance(a,torch.cuda.FloatTensor)

True

###   维度的查看

#### Dimension 0 /rank 0

In [15]:
torch.tensor(1.)

tensor(1.)

In [16]:
torch.tensor(1.3)

tensor(1.3000)

In [17]:
a = torch.tensor(2.2)

In [21]:
a.shape

torch.Size([])

In [22]:
len(a.shape)

0

In [23]:
a.size()

torch.Size([])

#### Dim1/rank1

In [24]:
torch.tensor([1.1])

tensor([1.1000])

In [25]:
torch.tensor([1.1,2.2])

tensor([1.1000, 2.2000])

In [29]:
torch.FloatTensor(1)  #和torch.Tensor()方法一样 且里面的数值为随机数

tensor([1.4013e-45])

In [30]:
torch.FloatTensor(2)  #如果参数只是数字m，则生成相应m个对应维度的张量

tensor([0.0000e+00, 4.5907e-41])

In [31]:
torch.FloatTensor(2,3)

tensor([[7.5556e+28, 5.2839e-11, 2.7604e+20],
        [1.7744e+28, 1.3458e-14, 3.9784e-14]])

In [33]:
data = np.ones(2)

In [34]:
data

array([1., 1.])

In [36]:
torch.from_numpy(data)  #从numpy的array类型转成torch类型

tensor([1., 1.], dtype=torch.float64)

In [37]:
a = torch.ones(2)

In [38]:
a.size()

torch.Size([2])

#### Dim 2

In [39]:
a = torch.randn(2,3)

In [40]:
a

tensor([[ 0.8081,  0.8148,  0.3431],
        [-0.1884, -0.4039, -0.3901]])

In [41]:
a.shape

torch.Size([2, 3])

In [42]:
a.size()

torch.Size([2, 3])

In [43]:
a.size(0)

2

In [44]:
a.size(1)

3

In [46]:
a.shape[1]

3

#### Dim 3

In [47]:
a = torch.rand(1,2,3)

In [48]:
a

tensor([[[0.1448, 0.1061, 0.5538],
         [0.1226, 0.8201, 0.0616]]])

In [49]:
a.size()

torch.Size([1, 2, 3])

In [51]:
a[0]    #对于维度在0的内容进行查看

tensor([[0.1448, 0.1061, 0.5538],
        [0.1226, 0.8201, 0.0616]])

In [53]:
list(a.shape)

[1, 2, 3]

#### Dim 4

In [55]:
a = torch.rand(2,3,28,28)

In [56]:
a

tensor([[[[0.3913, 0.7702, 0.7816,  ..., 0.4772, 0.5025, 0.6550],
          [0.8315, 0.9157, 0.9510,  ..., 0.9516, 0.3022, 0.5360],
          [0.7193, 0.0058, 0.2895,  ..., 0.2745, 0.8906, 0.1958],
          ...,
          [0.9767, 0.8712, 0.0094,  ..., 0.0743, 0.4029, 0.5524],
          [0.4496, 0.0614, 0.4702,  ..., 0.5747, 0.1962, 0.8715],
          [0.4448, 0.1035, 0.8796,  ..., 0.5205, 0.0418, 0.1537]],

         [[0.9692, 0.9610, 0.6815,  ..., 0.4274, 0.7677, 0.2618],
          [0.0608, 0.4698, 0.2328,  ..., 0.1326, 0.8146, 0.9929],
          [0.3475, 0.3848, 0.7697,  ..., 0.5878, 0.2994, 0.5917],
          ...,
          [0.0326, 0.0643, 0.7336,  ..., 0.3025, 0.6561, 0.6491],
          [0.5550, 0.7777, 0.5657,  ..., 0.7999, 0.9725, 0.0436],
          [0.0938, 0.1510, 0.3624,  ..., 0.6918, 0.3078, 0.9731]],

         [[0.8761, 0.4312, 0.6222,  ..., 0.3384, 0.7604, 0.4819],
          [0.3304, 0.6841, 0.5480,  ..., 0.4360, 0.9986, 0.9119],
          [0.4624, 0.7680, 0.1213,  ..., 0

In [57]:
a.shape

torch.Size([2, 3, 28, 28])

#### Mixed

In [58]:
a.shape

torch.Size([2, 3, 28, 28])

In [59]:
a.numel()  #总共的占用  2*3*28*28

4704

In [60]:
a.dim()

4

In [61]:
a = torch.tensor(1)

In [62]:
a.dim()

0