## operation

In [1]:
import torch
import numpy as np

### view/reshape

In [2]:
a = torch.rand(4,1,28,28)

In [3]:
a.view(4,28*28)

tensor([[0.5685, 0.5568, 0.3579,  ..., 0.1895, 0.5638, 0.4945],
        [0.3141, 0.5083, 0.4253,  ..., 0.3958, 0.8791, 0.1763],
        [0.1584, 0.5312, 0.4316,  ..., 0.8172, 0.1258, 0.6680],
        [0.2906, 0.5367, 0.0062,  ..., 0.6430, 0.8159, 0.4315]])

In [4]:
a.view(4,28*28).shape

torch.Size([4, 784])

In [5]:
a.view(4*28,28).shape

torch.Size([112, 28])

In [6]:
a.view(4*1,28,28).shape

torch.Size([4, 28, 28])

In [7]:
b = a.view(4,784)

In [8]:
b = a.view(4,28,28,1) #逻辑错误  logic Bug

### flexible but prone to corrput

In [9]:
a.view(4,783)

RuntimeError: shape '[4, 783]' is invalid for input of size 3136

### squeeze
 unsqueeze(index) ：在index的位置插入一个维度  index范围[-a.dim()-1,a.dim()+1)

In [10]:
a.shape

torch.Size([4, 1, 28, 28])

In [11]:
a.unsqueeze(0).shape   #在dim0维度加入一个维度

torch.Size([1, 4, 1, 28, 28])

In [12]:
a.unsqueeze(-1).shape

torch.Size([4, 1, 28, 28, 1])

In [13]:
a.unsqueeze(4).shape

torch.Size([4, 1, 28, 28, 1])

In [14]:
a.unsqueeze(-4).shape

torch.Size([4, 1, 1, 28, 28])

In [15]:
a.unsqueeze(-5).shape

torch.Size([1, 4, 1, 28, 28])

In [16]:
a.unsqueeze(5).shape

IndexError: Dimension out of range (expected to be in range of [-5, 4], but got 5)

In [18]:
a = torch.tensor([1.2,2.3])

In [19]:
a.unsqueeze(-1)

tensor([[1.2000],
        [2.3000]])

In [20]:
a.unsqueeze(0)

tensor([[1.2000, 2.3000]])

In [21]:
b = torch.rand(32)

In [22]:
b = b.unsqueeze(1).unsqueeze(2).unsqueeze(0)

In [23]:
b.shape

torch.Size([1, 32, 1, 1])

### unsqueeze

In [24]:
b.shape

torch.Size([1, 32, 1, 1])

In [25]:
b.squeeze().shape   #直接扁平化 将多维压成一维

torch.Size([32])

In [26]:
b.squeeze(0).shape

torch.Size([32, 1, 1])

In [27]:
b.squeeze(-1).shape

torch.Size([1, 32, 1])

In [28]:
b.squeeze(1).shape  #因为压缩的那一维不是1 所以不变

torch.Size([1, 32, 1, 1])

In [29]:
b.squeeze(-4).shape

torch.Size([32, 1, 1])

### expand

In [30]:
a = torch.rand(4,32,14,14)

In [31]:
b.shape

torch.Size([1, 32, 1, 1])

In [35]:
b.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [36]:
b.expand(-1,32,-1,-1).shape   #-1表示不变

torch.Size([1, 32, 1, 1])

### repeat  
与expand区别在于repeat是申请一片新的空间然后把数据复制进去

In [37]:
b.shape

torch.Size([1, 32, 1, 1])

In [38]:
b.repeat(4,32,1,1).shape

torch.Size([4, 1024, 1, 1])

In [39]:
b.repeat(4,1,1,1).shape

torch.Size([4, 32, 1, 1])

In [40]:
b.repeat(4,1,32,32).shape

torch.Size([4, 32, 32, 32])

### .t

In [41]:
b.t()   #.t()只能使用在于维度小于等于2的矩阵

RuntimeError: t() expects a tensor with <= 2 dimensions, but self is 4D

In [42]:
a = torch.randn(3,4)

In [43]:
a.t()

tensor([[-0.4872, -0.8502, -0.0793],
        [-2.2786, -0.6401, -1.6560],
        [ 0.3337, -1.3011,  0.6861],
        [ 0.8301, -0.5192, -0.3411]])

### transpose

In [44]:
a = torch.rand(4,3,32,32)

In [45]:
a.shape

torch.Size([4, 3, 32, 32])

In [46]:
a1 = a.transpose(1,3).view(4,3*32*32).view(4,3,32,32)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [47]:
a1 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)

In [48]:
a2 = a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)

In [49]:
a1.shape,a2.shape

(torch.Size([4, 3, 32, 32]), torch.Size([4, 3, 32, 32]))

In [50]:
torch.all(torch.eq(a,a1))

tensor(False)

In [51]:
torch.all(torch.eq(a,a2))

tensor(True)

### permute

In [52]:
a = torch.rand(4,3,28,28)

In [53]:
a.transpose(1,3).shape

torch.Size([4, 28, 28, 3])

In [54]:
b = torch.rand(4,3,28,32)

In [55]:
b.transpose(1,3).shape

torch.Size([4, 32, 28, 3])

In [56]:
b.transpose(1,3).transpose(1,2).shape

torch.Size([4, 28, 32, 3])

In [57]:
b.permute(0,2,3,1).shape

torch.Size([4, 28, 32, 3])