## Math operation

### add/minus/multiply/divide

In [4]:
import torch

In [5]:
a = torch.rand(3,4)

In [6]:
b = torch.rand(4)

In [8]:
a+b   #broadcast机制

tensor([[0.6217, 0.3050, 1.2174, 0.8734],
        [1.4195, 0.1732, 1.4134, 0.9378],
        [0.8348, 0.1298, 1.4412, 1.3280]])

In [9]:
torch.add(a,b)

tensor([[0.6217, 0.3050, 1.2174, 0.8734],
        [1.4195, 0.1732, 1.4134, 0.9378],
        [0.8348, 0.1298, 1.4412, 1.3280]])

In [10]:
torch.all(torch.eq(a-b,torch.sub(a,b)))

tensor(True)

In [11]:
torch.all(torch.eq(a*b,torch.mul(a,b)))

tensor(True)

In [12]:
torch.all(torch.eq(a/b,torch.div(a,b)))

tensor(True)

### matmul
torch.mm (only for 2d)  
torch.matmul  
@  

In [21]:
a = torch.full([2,2],3.)

In [22]:
a

tensor([[3., 3.],
        [3., 3.]])

In [23]:
b = torch.ones(2,2)

In [24]:
torch.mm(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [25]:
torch.matmul(a,b)

tensor([[6., 6.],
        [6., 6.]])

In [26]:
a@b

tensor([[6., 6.],
        [6., 6.]])

In [27]:
a = torch.rand(4,784)

In [28]:
b = torch.rand(4,784)

In [29]:
w = torch.rand(784,512) 

In [31]:
(b@w).shape

torch.Size([4, 512])

In [32]:
a = torch.rand(4,3,28,64)

In [33]:
b = torch.rand(4,3,64,32)

In [35]:
torch.mm(a,b).shape

RuntimeError: self must be a matrix

In [36]:
torch.matmul(a,b).shape   #多维矩阵的相乘就是最后两个维度相乘

torch.Size([4, 3, 28, 32])

In [37]:
b = torch.rand(4,1,64,32)

In [38]:
torch.matmul(a,b).shape  #相乘利用了broadcast机制

torch.Size([4, 3, 28, 32])

### power

In [39]:
a = torch.full([2,2],3)

In [40]:
a.pow(2)

tensor([[9, 9],
        [9, 9]])

In [41]:
a**2

tensor([[9, 9],
        [9, 9]])

In [43]:
aa = a**2

In [45]:
aa.rsqrt()  #每个元素取平方根后再取倒数

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333]])

In [46]:
aa**(0.5)

tensor([[3., 3.],
        [3., 3.]])

### exp log

In [47]:
a = torch.exp(torch.ones(2,2))  #e的次方

In [48]:
a

tensor([[2.7183, 2.7183],
        [2.7183, 2.7183]])

In [50]:
torch.log(a)  #log以e为底

tensor([[1., 1.],
        [1., 1.]])

### Approximation

.floor() .ceil()  
.round()  
.trunc()(小数点前数字) .frac()(小数点后面数字)  

In [52]:
a = torch.tensor(3.14)

In [53]:
a.floor(),a.ceil(),a.trunc(),a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [54]:
a = torch.tensor(3.499)

In [55]:
a.round()

tensor(3.)

In [56]:
a = torch.tensor(3.5)

In [57]:
a.round()

tensor(4.)

### clamp

gradient clipping  
(min)  
(min, max)

In [62]:
grad = torch.rand(2,3)*15

In [63]:
grad.max()

tensor(13.6933)

In [64]:
grad.median()

tensor(9.4789)

In [65]:
grad.clamp(10)   #小于10的全部变成10

tensor([[10.0000, 10.0000, 10.0000],
        [13.1776, 13.6933, 13.2330]])

In [66]:
grad

tensor([[ 3.9290,  7.5916,  9.4789],
        [13.1776, 13.6933, 13.2330]])

In [69]:
grad.clamp(5,10)  #小于5为5，大于10为10

tensor([[ 5.0000,  7.5916,  9.4789],
        [10.0000, 10.0000, 10.0000]])