## tensor advanced operation

### where

In [2]:
import torch

In [4]:
cond = torch.rand([2,2])

In [5]:
cond

tensor([[0.7635, 0.4552],
        [0.0142, 0.1702]])

In [8]:
a = torch.zeros(2,2)

In [9]:
a

tensor([[0., 0.],
        [0., 0.]])

In [10]:
b = torch.ones(2,2)

In [11]:
b

tensor([[1., 1.],
        [1., 1.]])

In [12]:
torch.where(cond>0.5,a,b)

tensor([[0., 1.],
        [1., 1.]])

### gather

In [21]:
prob = torch.randn(4,10)

In [22]:
idx = prob.topk(dim=1,k=3)

In [23]:
idx

torch.return_types.topk(
values=tensor([[1.9161, 1.2671, 1.2113],
        [1.0324, 0.4335, 0.0486],
        [0.8937, 0.6017, 0.5484],
        [2.0013, 0.8504, 0.7302]]),
indices=tensor([[4, 1, 7],
        [1, 5, 2],
        [2, 6, 4],
        [0, 1, 6]]))

In [24]:
idx = idx[1]

In [25]:
idx

tensor([[4, 1, 7],
        [1, 5, 2],
        [2, 6, 4],
        [0, 1, 6]])

In [26]:
label = torch.arange(10)+100

In [27]:
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [28]:
torch.gather(label.expand(4,10),dim=1,index=idx.long())

tensor([[104, 101, 107],
        [101, 105, 102],
        [102, 106, 104],
        [100, 101, 106]])